### ISSUE TITLE
 http://localhost:8080/wasm-featuredetect.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by hquu** [WonderlandEngine/wonderland-mind-ar-tracking#1]
http://localhost:8080/wasm-featuredetect.js net::ERR_ABORTED 404

**Comment by Squareys** [comment]
Hi @hquu!

This comes from the custom index.html template, probably in the example project. We removed `wasm-featuredetect.js` in, I think 0.9.1 or 0.9.0. If you create a new project with Wonderland Engine, you can check the differences to the new index.html file.

We'll have a look at this soon.

Best,
Jonathan

**Comment by Squareys** [comment]
Fixed with #2 , thank you @NSTCG !
