### ISSUE TITLE
您好，我想知道怎么运行您的代码

### ISSUE THREAD

**Issue by wowjuanjuan** [WonderlandEngine/wonderland-mind-ar-tracking#4]
大佬，我自己的midar项目抖动问题太厉害，而且不能像你youtube视频里那样镜头环绕着展示，请问我该怎么做

**Comment by Squareys** [comment]
您好！ @hiukim 可能能帮助.


可能能帮书 (我的中文不好):

你是在使用示例项目中的图像吗？它是在纸上还是在屏幕上？

**Comment by hiukim** [comment]
Hi, there are two things you can try:

1. update the filter parameters. Ref: https://hiukim.github.io/mind-ar-js-doc/quick-start/tracking-config.  But it's mostly just a tradeoff between delay and stability.

2. see if there is any room to improve the quality of your target image. Ref: https://www.mindar.org/how-to-choose-a-good-target-image-for-tracking-in-ar-part-3/
